### ISSUE TITLE
toTrytes - why only for ascii characters

### ISSUE THREAD

**Issue by Pomyk** [iotaledger/iota.js#118]
Wouldn't it be better to encode bytes, so you can transform for example arbitrary utf-8 strings into trytes?

**Comment by vbakke** [comment]
If you actually have a string of UTF-8 bytes, you can encode it with `toTrytes()`, since each byte (even the C3 like UTF-8 bytes) are below 255. 
 

A tryte must be within 27*27=729 (0x2D9). Therefore we cannot convert any unicode characters of \u02D9 or above.

I assume that your unicode strings are stored as UTF-16 in your JavaScript. 
Most European letters are below this threshold. But the Ogonek by itself ( ˛ or \u02DB), as well as many characters from other languages, would never be possible to encode in trytes. (At least not in _one_ _tryte_. :)


However, I just filed a bug #137, where I suggest that toTryte() should allow all values up to 728.

If that gets accepted and included, we can at least trytify most European words. As a side effect.

**Comment by obany** [comment]
Closing as this relates to an unmaintained branch of the library, which will be incompatible with the new Chrysalis release of the network.
