### ISSUE TITLE
prepareTransfers(): properly manage cases of addresses with checksum

### ISSUE THREAD

**Issue by pconfig** [iotaledger/iota.js#159]
When you specify your own inputs in the prepareTransfers call and use addresses with an added checksum you get the following error:

`Error: Illegal length provided
iota.js:1:24297
[10]</n.prototype.absorb
file:///C:/Users/TRI0002/Downloads/iota-address-generator-master/js/iota.js:1:24297
[4]</n.prototype.finalize
file:///C:/Users/TRI0002/Downloads/iota-address-generator-master/js/iota.js:1:18294
d
file:///C:/Users/TRI0002/Downloads/iota-address-generator-master/js/iota.js:1:8974
i
file:///C:/Users/TRI0002/Downloads/iota-address-generator-master/js/iota.js:1:8944
[2]</n.prototype.prepareTransfers/<
file:///C:/Users/TRI0002/Downloads/iota-address-generator-master/js/iota.js:1:11434
[21]</i.prototype.prepareResult
file:///C:/Users/TRI0002/Downloads/iota-address-generator-master/js/iota.js:1:43149
[21]</i.prototype.send/n.onreadystatechange
file:///C:/Users/TRI0002/Downloads/iota-address-generator-master/js/iota.js:1:40818`

I suggest to add a meaningful error message or to just strip the checksum from the input addresses.

**Comment by henriklaxhuber** [comment]
I wouldn't implicitly strip the checksum as that would be inconsistent with the operations of the rest of the library. Also, I find the error message to be meaningful enough.

Determining whether the added length is the result of an appended checksum would require first checking if the checksum is correct (otherwise those trytes could just be any garbage). This would be overengineering the error message and lead to less maintainable code.

**Comment by chrisdukakis** [comment]
I think we should validate the checksum if address is provided with it, and if is valid just remove it. This should be applied in all cases: `transfers`, `option.inputs` & `options.address/remainderAddress`. If checksum is invalid then we should throw error. A suitable error message would be `Invalid checksum for address: ADR....`

Note that right now [`v.1.0.0.alpha`](https://github.com/chrisdukakis/iota.lib.js/blob/next) [truncates checksums](https://github.com/chrisdukakis/iota.lib.js/blob/next/lib/api/extended/createPrepareTransfers.ts#L212) without validating. In the case of remainder address it does [nothing](https://github.com/chrisdukakis/iota.lib.js/blob/next/lib/api/extended/createPrepareTransfers.ts#L255).

In some rare cases involving human interaction and buggy code an invalid address results to invalid bundle. In case additional valid inputs are provided the user will have to reuse keys. Similar situation with invalid outputs could burn funds.

An additional enhancement could be to validate the signatures before broadcasting transactions. This works if inputs are passed without checksum and should also prevent any bugs in input management from taking effect.

@anyong @henriklaxhuber @pconfig what do you guys think?

**Comment by henriklaxhuber** [comment]
I think it makes more sense to define a checksum to be just that, a checksum. These should only come from human inputs, which to me means they should be handled by the caller, i.e. all library functions shouldn't need to expect addresses with or without checksums. Since the library provides simple utilities for validating and stripping these checksums, I really don't see the need to integrate them into every single API function.

It's really just a conceptual difference of separation of concerns. If the calling application is at a point where it's passing improper addresses to sensitive library functions, there is - in my opinion - a far greater issue on the caller's side.

**Comment by pph7** [comment]
Pardon me, but from an enduser point of view, it does not make sense that addresses can be specified everywhere else with checksum, but it throws an error if used in the remainderAddress field.

**Comment by obany** [comment]
Closing as this relates to an unmaintained branch of the library, which will be incompatible with the new Chrysalis release of the network.
