### ISSUE TITLE
mod in js is incorrect for large numbers

### ISSUE THREAD

**Issue by imerkle** [iotaledger/iota.js#335]
https://github.com/iotaledger/iota.js/blob/edd7a3d7b3c22219245a13561d307208027f5a76/packages/converter/src/trits.ts#L183

In js mod of large numbers is incorrect for example `55555555555555555555555555555553 % 2 = 0` in js whereas its clearly 1.
Therefore trytes is becoming different in js vs other languages.

**Comment by chrisdukakis** [comment]
Hi @imerkle , not just mod, everything stops working in JS if you exceed `Number.MAX_SAFE_INTEGER=9007199254740991`.

**Comment by imerkle** [comment]
```
    const seedHex = bip39.mnemonicToSeedHex(mnemonic, pass);
    const seedDec = new BigNumber(parseInt(seedHex, 16), 10);
    const seedTrits = fromValue(seedDec); 
    conts trytes = trytes(seedTrits);
```
Then how would i ideally create a iota trytes from a bip39 seed ?
When creating trytes using the above code `seedDec > 9007199254740991` therefore js seed is not the same as in other languages.

**Comment by chrisdukakis** [comment]
Hey @imerkle , it's unclear how secure this is. I think bip39 offers considerably [less entropy](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#generating-the-mnemonic) than simply generating 81 random trytes.
I'm sceptical about new wrappers like this, because people might want to login from wallet that doesn't recognize  the mnemonic format.
